apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: microservices-cluster
  region: us-east-1
  version: "1.32"

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

managedNodeGroups:
  - name: microservices-nodes
    instanceTypes: ["t3.micro", "t2.micro"]
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 20
    spot: false
    amiFamily: AmazonLinux2023
    maxPodsPerNode: 29
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
